FROM tryton/tryton:8.0

USER root
RUN pip3 install --break-system-packages --no-cache-dir \
      "trytond_party==8.0.*" \
      "trytond_country==8.0.*" \
      "trytond_currency==8.0.*" \
      "trytond_company==8.0.*" \
    && rm -rf /root/.cache/pip

COPY entrypoint.sh /entrypoint.sh
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
